<?php

namespace AppBundle\Repository;

/**
 *  OrdenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdenRepository extends \Doctrine\ORM\EntityRepository
{
}
