<?php

namespace AppBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
 
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;

class UsuarioRepository extends EntityRepository implements UserLoaderInterface
{
    
 
    public function loadUserByUsername($username)
    {
        return $this->createQueryBuilder('u')
            ->where('u.correo = :correo')
            ->setParameter('correo', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }
    
}
