<?php

namespace AppBundle\Repository;

/**
 * WishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistRepository extends \Doctrine\ORM\EntityRepository
{
}
