<?php

/* /doxygen/build/html/index.html */
class __TwigTemplate_1955200af291059425405789d78ce4534a19beca08905f60a2a05ea4e490d4fc extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_6b91006ac1d90d8fc41961cc56be932bee5acb1081f01d63b786c220d23828fb = $this->env->getExtension("Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension");
        $__internal_6b91006ac1d90d8fc41961cc56be932bee5acb1081f01d63b786c220d23828fb->enter($__internal_6b91006ac1d90d8fc41961cc56be932bee5acb1081f01d63b786c220d23828fb_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "/doxygen/build/html/index.html"));

        $__internal_9d8eb8d881d6d100947014203bf9433d1b86f0d8e17a5c1fbac12527226603a7 = $this->env->getExtension("Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension");
        $__internal_9d8eb8d881d6d100947014203bf9433d1b86f0d8e17a5c1fbac12527226603a7->enter($__internal_9d8eb8d881d6d100947014203bf9433d1b86f0d8e17a5c1fbac12527226603a7_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "/doxygen/build/html/index.html"));

        // line 1
        echo "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">
<html xmlns=\"http://www.w3.org/1999/xhtml\">
<head>
<meta http-equiv=\"Content-Type\" content=\"text/xhtml;charset=UTF-8\"/>
<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\"/>
<meta name=\"generator\" content=\"Doxygen 1.8.14\"/>
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>
<title>My Project: Main Page</title>
<link href=\"tabs.css\" rel=\"stylesheet\" type=\"text/css\"/>
<script type=\"text/javascript\" src=\"jquery.js\"></script>
<script type=\"text/javascript\" src=\"dynsections.js\"></script>
<link href=\"search/search.css\" rel=\"stylesheet\" type=\"text/css\"/>
<script type=\"text/javascript\" src=\"search/searchdata.js\"></script>
<script type=\"text/javascript\" src=\"search/search.js\"></script>
<link href=\"doxygen.css\" rel=\"stylesheet\" type=\"text/css\" />
</head>
<body>
<div id=\"top\"><!-- do not remove this div, it is closed by doxygen! -->
<div id=\"titlearea\">
<table cellspacing=\"0\" cellpadding=\"0\">
 <tbody>
 <tr style=\"height: 56px;\">
  <td id=\"projectalign\" style=\"padding-left: 0.5em;\">
   <div id=\"projectname\">My Project
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.14 -->
<script type=\"text/javascript\">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox(\"searchBox\", \"search\",false,'Search');
/* @license-end */
</script>
<script type=\"text/javascript\" src=\"menudata.js\"></script>
<script type=\"text/javascript\" src=\"menu.js\"></script>
<script type=\"text/javascript\">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
\$(function() {
  initMenu('',true,false,'search.php','Search');
  \$(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id=\"main-nav\"></div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id=\"MSearchSelectWindow\"
     onmouseover=\"return searchBox.OnSearchSelectShow()\"
     onmouseout=\"return searchBox.OnSearchSelectHide()\"
     onkeydown=\"return searchBox.OnSearchSelectKey(event)\">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id=\"MSearchResultsWindow\">
<iframe src=\"javascript:void(0)\" frameborder=\"0\" 
        name=\"MSearchResults\" id=\"MSearchResults\">
</iframe>
</div>

<div class=\"header\">
  <div class=\"headertitle\">
<div class=\"title\">My Project Documentation</div>  </div>
</div><!--header-->
<div class=\"contents\">
</div><!-- contents -->
<!-- start footer part -->
<hr class=\"footer\"/><address class=\"footer\"><small>
Generated by &#160;<a href=\"http://www.doxygen.org/index.html\">
<img class=\"footer\" src=\"doxygen.png\" alt=\"doxygen\"/>
</a> 1.8.14
</small></address>
</body>
</html>
";
        
        $__internal_6b91006ac1d90d8fc41961cc56be932bee5acb1081f01d63b786c220d23828fb->leave($__internal_6b91006ac1d90d8fc41961cc56be932bee5acb1081f01d63b786c220d23828fb_prof);

        
        $__internal_9d8eb8d881d6d100947014203bf9433d1b86f0d8e17a5c1fbac12527226603a7->leave($__internal_9d8eb8d881d6d100947014203bf9433d1b86f0d8e17a5c1fbac12527226603a7_prof);

    }

    public function getTemplateName()
    {
        return "/doxygen/build/html/index.html";
    }

    public function getDebugInfo()
    {
        return array (  25 => 1,);
    }

    /** @deprecated since 1.27 (to be removed in 2.0). Use getSourceContext() instead */
    public function getSource()
    {
        @trigger_error('The '.__METHOD__.' method is deprecated since version 1.27 and will be removed in 2.0. Use getSourceContext() instead.', E_USER_DEPRECATED);

        return $this->getSourceContext()->getCode();
    }

    public function getSourceContext()
    {
        return new Twig_Source("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">
<html xmlns=\"http://www.w3.org/1999/xhtml\">
<head>
<meta http-equiv=\"Content-Type\" content=\"text/xhtml;charset=UTF-8\"/>
<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\"/>
<meta name=\"generator\" content=\"Doxygen 1.8.14\"/>
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>
<title>My Project: Main Page</title>
<link href=\"tabs.css\" rel=\"stylesheet\" type=\"text/css\"/>
<script type=\"text/javascript\" src=\"jquery.js\"></script>
<script type=\"text/javascript\" src=\"dynsections.js\"></script>
<link href=\"search/search.css\" rel=\"stylesheet\" type=\"text/css\"/>
<script type=\"text/javascript\" src=\"search/searchdata.js\"></script>
<script type=\"text/javascript\" src=\"search/search.js\"></script>
<link href=\"doxygen.css\" rel=\"stylesheet\" type=\"text/css\" />
</head>
<body>
<div id=\"top\"><!-- do not remove this div, it is closed by doxygen! -->
<div id=\"titlearea\">
<table cellspacing=\"0\" cellpadding=\"0\">
 <tbody>
 <tr style=\"height: 56px;\">
  <td id=\"projectalign\" style=\"padding-left: 0.5em;\">
   <div id=\"projectname\">My Project
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.8.14 -->
<script type=\"text/javascript\">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox(\"searchBox\", \"search\",false,'Search');
/* @license-end */
</script>
<script type=\"text/javascript\" src=\"menudata.js\"></script>
<script type=\"text/javascript\" src=\"menu.js\"></script>
<script type=\"text/javascript\">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
\$(function() {
  initMenu('',true,false,'search.php','Search');
  \$(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id=\"main-nav\"></div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id=\"MSearchSelectWindow\"
     onmouseover=\"return searchBox.OnSearchSelectShow()\"
     onmouseout=\"return searchBox.OnSearchSelectHide()\"
     onkeydown=\"return searchBox.OnSearchSelectKey(event)\">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id=\"MSearchResultsWindow\">
<iframe src=\"javascript:void(0)\" frameborder=\"0\" 
        name=\"MSearchResults\" id=\"MSearchResults\">
</iframe>
</div>

<div class=\"header\">
  <div class=\"headertitle\">
<div class=\"title\">My Project Documentation</div>  </div>
</div><!--header-->
<div class=\"contents\">
</div><!-- contents -->
<!-- start footer part -->
<hr class=\"footer\"/><address class=\"footer\"><small>
Generated by &#160;<a href=\"http://www.doxygen.org/index.html\">
<img class=\"footer\" src=\"doxygen.png\" alt=\"doxygen\"/>
</a> 1.8.14
</small></address>
</body>
</html>
", "/doxygen/build/html/index.html", "/home/ubuntu/workspace/app/Resources/views/doxygen/build/html/index.html");
    }
}
